# Generated by Django 3.1 on 2021-02-02 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210121_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 21, 16, 38, 556558)),
        ),
    ]
