# Generated by Django 3.1 on 2021-02-15 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210202_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 10, 47, 47, 637865)),
        ),
    ]
