# Generated by Django 3.1 on 2021-06-30 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20210630_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 16, 37, 29, 777437)),
        ),
    ]
