# Generated by Django 3.1 on 2021-07-01 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20210701_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 14, 46, 52, 781741)),
        ),
    ]
