# Generated by Django 3.1 on 2021-11-08 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20211108_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 21, 15, 49, 419235)),
        ),
    ]
