# Generated by Django 3.1 on 2021-11-09 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20211109_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 15, 14, 58, 274609)),
        ),
    ]
